smtp:
  host: ssl://smtp.gmail.com
  user: &fromMail user@gmail.com
  pass: password
  port: 465

reportMail: pavlova@saytum.ru

fromMail: *fromMail

workHours:
  from: 10
  to: 22

data: users.php

min_age: 18

ignore_domains:
  - saytum.ru
  - domain.tld

subject: Hello subscriber

body: "<h1>Hello %s</h1>\
  You are subscribed to our mailing list"